// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFJ2A18eEGXi8wtAPSsSdF4sZqJWcOlSI',
    appId: '1:530440772344:web:4bce050d8312a194eb390d',
    messagingSenderId: '530440772344',
    projectId: 'visitelecoin',
    authDomain: 'visitelecoin.firebaseapp.com',
    storageBucket: 'visitelecoin.firebasestorage.app',
    measurementId: 'G-Y19QK3RG8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTtgW93Uwhc9qxCC6QJBFKqTHeFBhZE50',
    appId: '1:530440772344:android:6398b5066aa636aaeb390d',
    messagingSenderId: '530440772344',
    projectId: 'visitelecoin',
    storageBucket: 'visitelecoin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALguVULNEekbKzUcDjPZId5FrpnICNbps',
    appId: '1:530440772344:ios:452d80fb10f36244eb390d',
    messagingSenderId: '530440772344',
    projectId: 'visitelecoin',
    storageBucket: 'visitelecoin.firebasestorage.app',
    iosBundleId: 'com.example.visitelecoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALguVULNEekbKzUcDjPZId5FrpnICNbps',
    appId: '1:530440772344:ios:452d80fb10f36244eb390d',
    messagingSenderId: '530440772344',
    projectId: 'visitelecoin',
    storageBucket: 'visitelecoin.firebasestorage.app',
    iosBundleId: 'com.example.visitelecoin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFJ2A18eEGXi8wtAPSsSdF4sZqJWcOlSI',
    appId: '1:530440772344:web:ab6d56135868f0dfeb390d',
    messagingSenderId: '530440772344',
    projectId: 'visitelecoin',
    authDomain: 'visitelecoin.firebaseapp.com',
    storageBucket: 'visitelecoin.firebasestorage.app',
    measurementId: 'G-DF2W8SX05E',
  );
}
